## Database Properties
spring.datasource.url=jdbc:mysql:///users-db?cloudSqlInstance=project-58163151-c147-4cfa-9aa:us-central1:users-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=user&password=Uusers-mysql1&useSSL=FALSE

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

